# Generated by Django 2.2.11 on 2020-03-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20200319_0507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Вид покемона', 'verbose_name_plural': 'Виды покемонов'},
        ),
        migrations.AlterModelOptions(
            name='pokemonentity',
            options={'verbose_name': 'Покемон', 'verbose_name_plural': 'Покемоны'},
        ),
    ]
